/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
export namespace Components {
    interface AppRoot {
    }
    interface PageHome {
    }
    interface PageProfile {
        "match": MatchResults;
    }
    interface PlantComponent {
        "componentWillLoad": () => Promise<void>;
        "match": MatchResults;
        "value": number;
    }
    interface SliderComponent {
        "colour": string;
        "max": number;
        "min": number;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLPageProfileElement extends Components.PageProfile, HTMLStencilElement {
    }
    var HTMLPageProfileElement: {
        prototype: HTMLPageProfileElement;
        new (): HTMLPageProfileElement;
    };
    interface HTMLPlantComponentElement extends Components.PlantComponent, HTMLStencilElement {
    }
    var HTMLPlantComponentElement: {
        prototype: HTMLPlantComponentElement;
        new (): HTMLPlantComponentElement;
    };
    interface HTMLSliderComponentElement extends Components.SliderComponent, HTMLStencilElement {
    }
    var HTMLSliderComponentElement: {
        prototype: HTMLSliderComponentElement;
        new (): HTMLSliderComponentElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "page-home": HTMLPageHomeElement;
        "page-profile": HTMLPageProfileElement;
        "plant-component": HTMLPlantComponentElement;
        "slider-component": HTMLSliderComponentElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface PageHome {
    }
    interface PageProfile {
        "match"?: MatchResults;
    }
    interface PlantComponent {
        "match"?: MatchResults;
        "value"?: number;
    }
    interface SliderComponent {
        "colour"?: string;
        "max"?: number;
        "min"?: number;
        "onValueChanged"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "page-home": PageHome;
        "page-profile": PageProfile;
        "plant-component": PlantComponent;
        "slider-component": SliderComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "page-profile": LocalJSX.PageProfile & JSXBase.HTMLAttributes<HTMLPageProfileElement>;
            "plant-component": LocalJSX.PlantComponent & JSXBase.HTMLAttributes<HTMLPlantComponentElement>;
            "slider-component": LocalJSX.SliderComponent & JSXBase.HTMLAttributes<HTMLSliderComponentElement>;
        }
    }
}
